apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/1 * * * *" # 没分钟执行一次，格式与 linux cron 一致
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: busybox
              command: ["echo", "hello cron job!"]
          restartPolicy: OnFailure
